//Create a TS file called AcademyDAO (DAO --> Data access object). This will have methods for creating, deleting, updating and querying academy.
 
const mysql = require('mysql');
export const connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'root',
  password : '12#Ramesh',
  server   : 'MySQL57', 
  database : 'rameshdb'
});
connection.connect(function(err){
	if(err)throw err;
	});

export class AcModel {

	constructor(private name:string, private location: string, private description: string, private image: string){}

	query(){
		connection.query('SELECT sno, name, location, description, image FROM academy_info group by sno', function(err,rows){
				if(err) throw err;
				console.log(rows);
	})}

	update(){
		connection.query(`UPDATE academy_info SET location = '${this.location}' WHERE sno = '${this.sno}'`, function(err,rows){
				if(err) throw err;
				console.log(rows);
	})}

	addRecord(){
		connection.query(`INSERT INTO academy_info (sno,name, location, description,image) VALUES ( 3,'${this.name}','${this.location}','${this.description}','${this._image}')`, function(err,rows){
				if(err) throw err;
				console.log(rows);
	})}

	delete(){
		connection.query('DELETE FROM academy_info WHERE sno = 3', function(err,rows){
				if(err) throw err;
				console.log(rows);
	})}
	}

//STORING AUTOGENERATED SNO IS PENDING. WORKING ON IT.
